# Generated by Django 2.1.7 on 2019-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название Группы')),
                ('country', models.CharField(default='', max_length=200, verbose_name='Страна')),
                ('style', models.CharField(default='', max_length=30, verbose_name='Жанр')),
                ('age', models.IntegerField(default=1950, verbose_name='Год деятельности')),
                ('songs', models.TextField(default='', verbose_name='Песни')),
                ('sostav', models.TextField(default='', verbose_name='Состав группы')),
                ('alboms', models.TextField(default='', verbose_name='Альбомы')),
                ('history', models.TextField(default='', verbose_name='История группы')),
            ],
        ),
    ]
