# Generated by Django 2.2 on 2019-09-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя режиссера')),
                ('description', models.TextField(verbose_name='Описание режиссера')),
                ('image', models.URLField(default='', max_length=300, verbose_name='Ссылка на фото режиссера')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фиьма')),
                ('image', models.URLField(default='', max_length=300, verbose_name='Ссылка на фото группы')),
                ('trailer', models.URLField(default='', max_length=300, verbose_name='Ссылка на фото трейлер фильма')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Director')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='year',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
