# Generated by Django 2.2 on 2019-09-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190918_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='image',
        ),
    ]
